const {useState, useEffect, useRef} = React;
const EMAIL = 'kayorodrigodzn@gmail.com';
const ALL_PROJECTS = [DELIVERY_CASE, ...PROJECTS];
const Arrow = ({down=false}) => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true" style={down?{transform:'rotate(90deg)'}:undefined}><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.5"/></svg>;
const Out = () => <span aria-hidden="true">↗</span>;
const projectTitle=p=>typeof p.title==='string'?p.title:p.title.pt;
function readRoute(){
  const u=new URL(location.href); let path=u.searchParams.get('caminho')==='servicos'?'servicos':'contratacao';
  let profile=u.searchParams.get('perfil')==='desenvolvimento'?'desenvolvimento':'logistica';
  let service=Object.hasOwn(SERVICES,u.searchParams.get('servico'))?u.searchParams.get('servico'):'automacao';
  const id=u.hash.startsWith('#case/')?u.hash.slice(6):null;
  const project=Object.hasOwn(PROJECT_NOTES,id)?id:null;
  if(project){
    if(path==='contratacao'&&!PROFILES[profile].projects.includes(project)) profile=['comprovantes','dashmytracking'].includes(project)?'logistica':'desenvolvimento';
    if(project==='judicial'){path='servicos';service='sites';}
    if(path==='servicos'&&!SERVICES[service].projects.includes(project)) service=['comprovantes','dashmytracking'].includes(project)?'automacao':'aplicacoes';
  }
  return {path,profile,service,project};
}
function updateUrl(route,push=true){
  const u=new URL(location.href);u.searchParams.set('caminho',route.path);u.searchParams.delete('lang');
  if(route.path==='contratacao'){u.searchParams.set('perfil',route.profile);u.searchParams.delete('servico');}
  else{u.searchParams.set('servico',route.service);u.searchParams.delete('perfil');}
  u.hash=route.project?'case/'+route.project:'';
  history[push?'pushState':'replaceState'](null,'',u.pathname+u.search+u.hash);
}
function Project({p,index,open,onToggle}){
  const n=PROJECT_NOTES[p.id];const Diagram=p.diagram&&window.DIAGRAMS?.[p.diagram];
  return <article className={'project '+(open?'expanded':'')} id={'project-'+p.id}>
    <button className="project-heading" onClick={onToggle} aria-expanded={open} aria-controls={'case-'+p.id}>
      <span className="project-number">0{index+1}</span>
      <span className="project-overview"><span className="eyebrow project-kind">{n.label}</span><span className="project-title">{projectTitle(p)}</span><span className="project-description">{n.blurb}</span><span className="tags">{(n.tags||p.tags).slice(0,4).map(t=><span key={t}>{t}</span>)}</span></span>
      <span className="case-toggle"><span>{open?'Fechar case':'Explorar case'}</span><span className="plus" aria-hidden="true">{open?'−':'+'}</span></span>
    </button>
    <div id={'case-'+p.id} hidden={!open} className="case-content">
      <div className="case-grid"><div><span className="eyebrow">O desafio</span><p>{p.id==='fluxo'?'Organizar as finanças em torno de objetivos e de uma jornada de planejamento, além do registro de gastos.':p.id==='aura'?'Reunir catálogo, acesso aos cursos, pagamentos e emissão de certificados verificáveis em uma plataforma própria.':p.study.problem.pt}</p><span className="eyebrow">Minha participação</span><p>{n.role}</p></div><div><span className="eyebrow">O que construí</span><ul>{p.study.build.pt.slice(0,3).map(t=><li key={t}>{t}</li>)}</ul><span className="eyebrow">Entrega</span><p>{n.result}</p></div></div>
      {Diagram&&<details className="architecture"><summary>Ver arquitetura técnica <span aria-hidden="true">+</span></summary><div className="diagram-frame"><Diagram lang="pt"/></div></details>}
      <div className="case-bottom"><span>{n.proof}</span><div>{p.links.map(l=><a key={l.href} href={l.href} target="_blank" rel="noopener noreferrer">{l.kind==='repo'?'Ver código'+(p.links.length>1?' · '+l.label.pt:''):'Visitar projeto'} <Out/></a>)}</div></div>
    </div>
  </article>
}
function App(){
  const [route,setRoute]=useState(readRoute);
  const [dark,setDark]=useState(()=>{try{return (localStorage.getItem('theme')||'light')==='dark'}catch{return false}});
  const [drafts,setDrafts]=useState({});
  const draftKey=route.path==='contratacao'?'vaga-'+route.profile:'servico-'+route.service;
  const {context='',company='',deadline=''}=drafts[draftKey]||{};
  const setDraft=(key,value)=>setDrafts(prev=>({...prev,[draftKey]:{...prev[draftKey],[key]:value}}));
  const setContext=value=>setDraft('context',value),setCompany=value=>setDraft('company',value),setDeadline=value=>setDraft('deadline',value);
  const [notice,setNotice]=useState('');const [menu,setMenu]=useState(false);const [modal,setModal]=useState('summary');const dialog=useRef(null);const [egg,setEgg]=useState(false);
  const hire=route.path==='contratacao';const profile=PROFILES[route.profile];const service=SERVICES[route.service];const selection=hire?profile:service;
  useEffect(()=>{const restore=()=>setRoute(readRoute());window.addEventListener('popstate',restore);window.addEventListener('hashchange',restore);return()=>{window.removeEventListener('popstate',restore);window.removeEventListener('hashchange',restore)}},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('theme',dark?'dark':'light')}catch{}},[dark]);
  useEffect(()=>{if(route.project)requestAnimationFrame(()=>document.getElementById('project-'+route.project)?.scrollIntoView({block:'start'}));},[]);
  useEffect(()=>{document.title='Kayo Santos — '+(hire?profile.label:service.label);},[route.path,route.profile,route.service]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t)},[notice]);
  useKonami(React.useCallback(()=>setEgg(e=>!e),[]));
  const choose=changes=>{const next={...route,...changes,project:null};setRoute(next);updateUrl(next);setNotice('');};
  const toggleProject=id=>{const next={...route,project:route.project===id?null:id};setRoute(next);updateUrl(next,false)};
  const subject=hire?'Oportunidade · '+profile.label:'Projeto · '+service.label;
  const message=hire?`Olá, Kayo!\n\nGostaria de conversar sobre uma oportunidade em ${profile.label}.${company.trim()?'\nEmpresa / vaga: '+company.trim():''}${context.trim()?'\n\nSobre a oportunidade:\n'+context.trim():''}\n\nPodemos conversar?`:`Olá, Kayo!\n\nTenho interesse em ${service.label.toLowerCase()}.${company.trim()?'\nNome / empresa: '+company.trim():''}${context.trim()?'\n\nO que preciso resolver:\n'+context.trim():''}${deadline.trim()?'\nPrazo desejado: '+deadline.trim():''}\n\nPodemos conversar sobre o escopo?`;
  const mailto='mailto:'+EMAIL+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(message);
  const copy=async(value,success)=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(value);setNotice(success)}catch{setNotice('Não foi possível copiar automaticamente. Selecione e copie o texto na prévia da mensagem.');setModal('message');dialog.current?.showModal()}};
  const openDialog=type=>{setModal(type);dialog.current?.showModal()};
  return <>
    <a className="skip-link" href="#perfil">Pular para o conteúdo</a>
    <header className="site-header"><a className="brand" href="#inicio" aria-label="Kayo Santos — início"><span className="brand-mark">K</span><span>kayo<span className="accent">.</span>dev</span></a><nav className={menu?'nav menu-open':'nav'} aria-label="Navegação principal"><a onClick={()=>setMenu(false)} href="#perfil">Perfil & projetos</a><a onClick={()=>setMenu(false)} href="#contato">Vamos conversar <Out/></a></nav><div className="header-actions"><button className="theme-toggle" onClick={()=>setDark(!dark)} aria-label={dark?'Ativar tema claro':'Ativar tema escuro'} aria-pressed={dark}>{dark?'☀':'☾'}</button><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Abrir menu">{menu?'Fechar':'Menu'}</button></div></header>
    <main>
      <section className="hero section-wrap" id="inicio" aria-labelledby="hero-title"><div className="hero-meta"><span><i className="status-dot"/> ABERTO A CONVERSAS E OPORTUNIDADES</span><span>GOIÂNIA, BR <span className="meta-symbol">↗</span></span></div><div className="hero-grid"><div className="hero-identity"><h1 id="hero-title">Kayo<br/>Santos<span className="accent">.</span></h1><div className="personal-note"><img src="assets/kayo.webp" width="52" height="64" alt="Kayo Santos"/><p>Logística na prática.<br/>Tecnologia para ir além.</p></div></div><div className="hero-direction"><p className="hero-statement">Entendo a operação.<br/><em>Construo a solução.</em></p><p className="hero-description">Experiência em transporte, dados e desenvolvimento. Escolha o que faz sentido para você.</p><div className="path-selector" role="group" aria-label="O que trouxe você aqui"><p className="eyebrow">O QUE TROUXE VOCÊ AQUI?</p><button aria-pressed={hire} className={'path-option '+(hire?'selected':'')} onClick={()=>choose({path:'contratacao'})}><span className="path-icon" aria-hidden="true">01</span><span><strong>Quero contratar você</strong><small>Conheça meus perfis profissionais</small></span><Arrow/></button><button aria-pressed={!hire} className={'path-option '+(!hire?'selected':'')} onClick={()=>choose({path:'servicos'})}><span className="path-icon" aria-hidden="true">02</span><span><strong>Preciso de um serviço</strong><small>Encontre uma solução para seu negócio</small></span><Arrow/></button></div><a className="explore-link" href="#perfil">{hire?'Explorar perfis e experiência':'Explorar serviços e projetos'} <Arrow down/></a></div></div><div className="hero-footer"><span>OPERAÇÃO <b>✳</b> DADOS <b>✳</b> SOFTWARE <b>✳</b> DESIGN</span><span>UM PERFIL. MAIS DE UMA FORMA DE CONTRIBUIR.</span></div></section>
      <section className="work section-wrap" id="perfil" aria-labelledby="work-title"><div className="section-eyebrow"><span>01 / {hire?'PARA RECRUTADORES':'PARA CLIENTES'}</span><span>ESCOLHA SEU CAMINHO</span></div><div className="section-intro"><h2 id="work-title">{hire?'A experiência certa\npara a sua equipe.':'O próximo passo\ndo seu negócio.'}</h2><p>{hire?'Duas frentes de atuação, com experiências e projetos próprios. Selecione o perfil que combina com a oportunidade.':'Do processo que precisa melhorar à ideia que precisa ganhar forma. Escolha o tipo de projeto.'}</p></div>
        <div className={'choice-tabs '+(!hire?'service-tabs':'')} role="group" aria-label={hire?'Selecionar perfil profissional':'Selecionar serviço'}>{Object.entries(hire?PROFILES:SERVICES).map(([key,value])=><button key={key} aria-pressed={(hire?route.profile:route.service)===key} onClick={()=>choose(hire?{profile:key}:{service:key})}>{!hire&&<span>{value.number}</span>}{value.label}<span className="selection-mark" aria-hidden="true">↗</span></button>)}</div>
        <div className="selected-profile" id="selected-path"><div className="profile-copy"><div className="eyebrow accent">{hire?profile.role:'COMO POSSO AJUDAR'}</div><h3>{selection.title}</h3><p>{selection.intro}</p>{hire?<div className="tags profile-stack">{profile.stack.map(t=><span key={t}>{t}</span>)}</div>:<p className="service-scope">{service.scope}</p>}<div className="profile-links"><a className="text-link" href="#contato">{hire?'Conversar sobre uma vaga':'Conversar sobre este serviço'} <Arrow/></a>{hire&&<button className="subtle-link" onClick={()=>openDialog('summary')}>Resumo do perfil <Out/></button>}</div></div><aside className="profile-evidence">{hire?<><span className="eyebrow">ONDE POSSO CONTRIBUIR</span><ul className="strengths">{profile.strengths.map((s,i)=><li key={s}><span>0{i+1}</span>{s}</li>)}</ul></>:<><span className="eyebrow">O QUE PODEMOS CONSTRUIR</span><p className="service-output">{service.output}</p><ol className="service-process"><li><span>01</span> Entender o problema</li><li><span>02</span> Combinar escopo e entregas</li><li><span>03</span> Construir e validar</li></ol></>}</aside></div>
        <div className="projects-label"><h3>{hire?'Projetos que sustentam esse perfil':'Trabalhos relacionados'}</h3><span className="eyebrow">{selection.projects.length.toString().padStart(2,'0')} CASES · CLIQUE PARA EXPLORAR</span></div><div className="project-list">{selection.projects.map((id,i)=><Project key={id} p={ALL_PROJECTS.find(p=>p.id===id)} index={i} open={route.project===id} onToggle={()=>toggleProject(id)}/>)}</div>
        {hire&&<details className="experience"><summary><span>Trajetória & formação</span><span className="eyebrow">VER EXPERIÊNCIA <span aria-hidden="true">+</span></span></summary><div className="experience-list">{profile.experience.map(e=><article key={e.title}><span className="eyebrow">{e.date}</span><div><h4>{e.title}</h4><span>{e.company}</span><p>{e.text}</p></div></article>)}</div></details>}
      </section>
      <section className="contact section-wrap" id="contato" aria-labelledby="contact-title"><div className="section-eyebrow"><span>02 / VAMOS CONVERSAR</span><span>DE UMA BOA CONVERSA, UM BOM COMEÇO.</span></div><div className="contact-grid"><div><h2 id="contact-title">{hire?'Sua próxima\ncontratação?':'Vamos tirar isso\ndo papel.'}<span className="accent">↗</span></h2><p className="contact-intro">{hire?'Conte sobre a oportunidade e o que você espera de quem vai fazer parte da equipe.':'Conte o que você precisa resolver. A primeira conversa serve para entender o problema e definir um escopo possível.'}</p><a className="email-link" href={'mailto:'+EMAIL}>{EMAIL}</a><div className="social-links"><a href="https://www.linkedin.com/in/kayo-santos/" target="_blank" rel="noopener noreferrer">LinkedIn <Out/></a><a href="https://github.com/kayoinreality" target="_blank" rel="noopener noreferrer">GitHub <Out/></a></div></div><div className="contact-builder"><span className="eyebrow">{hire?'OPORTUNIDADE':'SEU PROJETO'} / <span className="accent">{selection.label}</span></span><label htmlFor="company">{hire?'Empresa ou nome da vaga':'Seu nome ou empresa'} <small>(opcional)</small></label><input id="company" maxLength="120" autoComplete="organization" value={company} onChange={e=>setCompany(e.target.value)} placeholder={hire?'Ex.: Analista de Logística · Sua empresa':'Como posso chamar você?'}/><label htmlFor="context">{hire?'Sobre a oportunidade':'O que você precisa resolver?'} <small>(opcional)</small></label><textarea id="context" maxLength="1800" rows="3" value={context} onChange={e=>setContext(e.target.value)} placeholder={hire?'Conte sobre a função, o modelo de trabalho e os principais desafios.':service.placeholder}/>{!hire&&<><label htmlFor="deadline">Prazo desejado <small>(opcional)</small></label><input id="deadline" maxLength="80" value={deadline} onChange={e=>setDeadline(e.target.value)} placeholder="Ex.: próximo mês ou ainda a definir"/></>}<a className="btn-primary" id="email-action" href={mailto}>Preparar conversa por e-mail <Arrow/></a><div className="contact-secondary"><button onClick={()=>openDialog('message')}>Ver mensagem</button><button onClick={()=>copy(message,'Mensagem copiada. Cole no seu e-mail para continuar.')}>Copiar mensagem</button></div><p className="form-note">Abre seu aplicativo de e-mail com uma mensagem pronta. Você revisa e envia por lá. Nada é enviado por esta página.</p></div></div></section>
    </main><footer className="section-wrap"><div className="footer-meta"><span>© 2026 Kayo Santos</span><span>OPERAÇÃO REAL. SOLUÇÕES COM INTENÇÃO.</span><a href="#inicio">Voltar ao início ↑</a></div><div className="footer-word" aria-hidden="true">KAYO<span className="accent">.</span></div>{egg&&<p className="egg">A força está nos detalhes. ✦</p>}</footer>
    <div className="status-message" role="status" aria-live="polite">{notice}</div><span className="sr-only" role="status" aria-live="polite">Caminho selecionado: {hire?'Contratação — ':'Serviços — '}{selection.label}</span>
    <dialog ref={dialog} className={'review-dialog '+(modal==='summary'?'summary-dialog':'message-dialog')} aria-labelledby="dialog-title"><button className="dialog-close" onClick={()=>dialog.current.close()} aria-label="Fechar janela">Fechar ×</button>{modal==='summary'?<><div className="print-content"><span className="eyebrow">RESUMO PROFISSIONAL</span><h2 id="dialog-title">Kayo Santos<span className="accent">.</span></h2><h3>{profile.role}</h3><p>{profile.intro}</p><h4>Competências</h4><p>{profile.stack.join(' · ')}</p><h4>Experiência e formação</h4>{profile.experience.map(e=><div className="resume-entry" key={e.title}><strong>{e.title}</strong><p>{e.company} · {e.date}</p><p>{e.text}</p></div>)}<h4>Projetos selecionados</h4>{profile.projects.map(id=><p key={id}><strong>{projectTitle(ALL_PROJECTS.find(p=>p.id===id))}</strong> — {PROJECT_NOTES[id].result}</p>)}<h4>Contato</h4><p>{EMAIL}<br/>linkedin.com/in/kayo-santos · github.com/kayoinreality</p></div><button className="btn-primary" onClick={()=>window.print()}>Imprimir / salvar em PDF <Out/></button></>:<><span className="eyebrow">PRONTA PARA VOCÊ REVISAR</span><h2 id="dialog-title">Sua mensagem.</h2><p className="message-recipient">Para: {EMAIL}<br/>Assunto: {subject}</p><pre className="message-preview">{message}</pre><a className="btn-primary" href={mailto}>Abrir no e-mail <Arrow/></a></>}</dialog>
  </>;
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
